### ISSUE TITLE
Initial FastAPI application

### ISSUE THREAD

**Issue by isedwards** [opencdms-dev/legacy-opencdms-api#1]
The `opencdms-server` repository will contain a FastAPI application that exposes web API(s) for use by [opencdms-app](https://github.com/opencdms/opencdms-app) and other applications. One of the dependencies of opencdms-server will be `pip install opencdms` (which comes from our pyopencdms repo).

Initially we want to do: `from opencdms.models.climsoft. v4_1_1_core import Station`

We can then read/GET the details of individual stations from the ‘station’ table using the Web API.

**Comment by Shaibujnr** [comment]
https://github.com/opencdms/opencdms-server/pull/3

**Comment by isedwards** [comment]
Resolved by #3
